CREATE TYPE "public"."accounting_method_enum" AS ENUM('cash', 'accrual');--> statement-breakpoint
CREATE TYPE "public"."business_size_enum" AS ENUM('micro', 'small', 'medium', 'large');--> statement-breakpoint
CREATE TYPE "public"."coa_template_enum" AS ENUM('malaysian_sme', 'malaysian_services', 'malaysian_trading', 'malaysian_manufacturing', 'malaysian_fnb', 'custom', 'import');--> statement-breakpoint
CREATE TYPE "public"."company_type" AS ENUM('sole_proprietorship', 'partnership', 'llp', 'sdn_bhd', 'bhd', 'npo', 'cooperative', 'government', 'branch', 'representative', 'other');--> statement-breakpoint
CREATE TYPE "public"."migration_source_enum" AS ENUM('none', 'quickbooks', 'xero', 'sage', 'myob', 'wave', 'zoho_books', 'freshbooks', 'sql_accounting', 'autocount', 'ubs', 'million', 'spreadsheet', 'manual', 'other');--> statement-breakpoint
CREATE TYPE "public"."sst_status_enum" AS ENUM('not_registered', 'registered', 'voluntary', 'exempt', 'deregistered');--> statement-breakpoint
CREATE TABLE "company_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"legal_name" varchar(255),
	"trade_name" varchar(255),
	"company_type" "company_type",
	"registration_number" varchar(50),
	"old_registration_number" varchar(50),
	"date_of_incorporation" date,
	"address_line_1" varchar(255),
	"address_line_2" varchar(255),
	"address_line_3" varchar(255),
	"city" varchar(100),
	"postcode" varchar(10),
	"state" varchar(100),
	"state_code" varchar(2),
	"country" varchar(2) DEFAULT 'MY',
	"primary_phone" varchar(20),
	"secondary_phone" varchar(20),
	"primary_email" varchar(255),
	"website" varchar(255),
	"contact_persons" jsonb,
	"msic_code" varchar(5),
	"msic_description" varchar(255),
	"industry_type" varchar(100),
	"business_size" "business_size_enum",
	"nature_of_business" text,
	"main_products" text,
	"annual_revenue_range" varchar(50),
	"accounting_method" "accounting_method_enum" DEFAULT 'accrual',
	"fiscal_year_start_month" integer DEFAULT 1,
	"fiscal_year_start_day" integer DEFAULT 1,
	"default_currency" varchar(3) DEFAULT 'MYR',
	"multi_currency_enabled" boolean DEFAULT false,
	"coa_template" "coa_template_enum",
	"tin_number" varchar(20),
	"sst_status" "sst_status_enum" DEFAULT 'not_registered',
	"sst_registration_number" varchar(50),
	"sst_registration_date" date,
	"sst_deregistration_date" date,
	"tourism_tax_number" varchar(50),
	"einvoice_enabled" boolean DEFAULT false,
	"einvoice_effective_date" date,
	"einvoice_tin" varchar(20),
	"einvoice_brn" varchar(30),
	"epf_employer_number" varchar(20),
	"socso_employer_number" varchar(20),
	"eis_employer_number" varchar(20),
	"hrdf_levy_number" varchar(20),
	"pcb_file_number" varchar(20),
	"bank_accounts" jsonb,
	"logo_url" text,
	"logo_base64" text,
	"signature_url" text,
	"signature_base64" text,
	"brand_primary_color" varchar(7),
	"brand_secondary_color" varchar(7),
	"invoice_prefix" varchar(10) DEFAULT 'INV-',
	"quotation_prefix" varchar(10) DEFAULT 'QT-',
	"credit_note_prefix" varchar(10) DEFAULT 'CN-',
	"debit_note_prefix" varchar(10) DEFAULT 'DN-',
	"bill_prefix" varchar(10) DEFAULT 'BILL-',
	"default_payment_terms" varchar(100),
	"default_payment_terms_days" integer DEFAULT 30,
	"invoice_notes" text,
	"invoice_terms" text,
	"quotation_notes" text,
	"quotation_terms" text,
	"quotation_validity_days" integer DEFAULT 30,
	"migration_source" "migration_source_enum" DEFAULT 'none',
	"migration_source_other" varchar(100),
	"migration_date" date,
	"opening_balance_date" date,
	"migration_notes" text,
	"previous_fiscal_year_end" date,
	"has_pending_migration" boolean DEFAULT false,
	"onboarding_completed" boolean DEFAULT false,
	"onboarding_completed_at" timestamp,
	"onboarding_skipped" boolean DEFAULT false,
	"onboarding_skipped_at" timestamp,
	"profile_completeness" integer DEFAULT 0,
	"last_profile_update_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "company_profiles_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "company_profiles" ADD CONSTRAINT "company_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;