const SOCIALS = {
  GITHUB: "https://github.com/hazlijohar95/open-bookkeeping.com",
};

const LEGAL = {
  PRIVACY: "/privacy",
  TERMS: "/terms",
};

export const LINKS = {
  SOCIALS: SOCIALS,
  LEGAL: LEGAL,
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  INVOICES: "/invoices",
  QUOTATIONS: "/quotations",
  CREDIT_NOTES: "/credit-notes",
  DEBIT_NOTES: "/debit-notes",
  CUSTOMERS: "/customers",
  VENDORS: "/vendors",
  BILLS: "/bills",
  BANK_FEEDS: "/bank-feeds",
  CHART_OF_ACCOUNTS: "/chart-of-accounts",
  JOURNAL_ENTRIES: "/journal-entries",
  TRIAL_BALANCE: "/trial-balance",
  PROFIT_LOSS: "/profit-loss",
  BALANCE_SHEET: "/balance-sheet",
  SST: "/sst",
  VAULT: "/vault",
  ANALYTICS: "/analytics",
  BLOGS: "/blogs",
  ASSETS: "/assets",
  SETTINGS: "/settings",
  STATEMENTS: "/statements",
  DEVELOPER: "/developer",
  DEVELOPER_API_KEYS: "/developer/api-keys",
  DEVELOPER_WEBHOOKS: "/developer/webhooks",
  DATA_FLOW: "/data-flow",
  FIXED_ASSETS: "/fixed-assets",
  AGENT: "/agent",
  EMPLOYEES: "/employees",
  PAYROLL_RUNS: "/payroll",
  CREATE: {
    INVOICE: "/create/invoice",
    QUOTATION: "/create/quotation",
    CREDIT_NOTE: "/create/credit-note",
    DEBIT_NOTE: "/create/debit-note",
  },
  // Superadmin routes
  SUPERADMIN: {
    DASHBOARD: "/superadmin",
    USERS: "/superadmin/users",
    USER_DETAIL: "/superadmin/users/:id",
    ORGANIZATIONS: "/superadmin/organizations",
    ORGANIZATION_DETAIL: "/superadmin/organizations/:id",
    ANALYTICS: "/superadmin/analytics",
    AGENT: "/superadmin/agent",
    SUBSCRIPTIONS: "/superadmin/subscriptions",
    REVENUE: "/superadmin/revenue",
    SETTINGS: "/superadmin/settings",
    AUDIT_LOGS: "/superadmin/audit",
  },
};
